version: '3.4'

services:
  socketioadapter:
    image: socketioadapter
    build:
      context: node_modules/socket.io-adapter
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
